config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"

  get 'toppages/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get :likes
    end
  end
  resources :categories, only: %i[create]
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :post, optional: true
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 255 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :categories
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save { email.downcase! }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false } 

  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :like_posts, through: :likes, source: :post

  def like(post)
    likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    like = likes.find_by(post_id: post.id)
    like.destroy if like
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend

  private

  def require_user_logged_in?
    redirect_to login_url unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new(category_params)
    @category.save
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        flash[:success] = 'コメントを投稿しました'
        redirect_to post_path(@post)
      else
        flash[:danger] = 'コメントの投稿に失敗しました'
        redirect_back(fallback_location: post_path)
      end
    end
  
    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      flash[:success] = 'コメントを削除しました'
      redirect_to post_path(@post)
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:comment)
    end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    flash[:success] = 'お気に入り登録しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    flash[:success] = 'お気に入り登録を外しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_target_post, only: %i[show destroy]
  before_action :require_user_logged_in?

  def index
    @pagy, @posts = pagy(params[:category_id].present? ? Category.find(params[:category_id]).posts.order('id DESC') : Post.order('id DESC'))
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "「#{@post.title}」を作成しました"
      redirect_to @post
    else   
      flash.now[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "「#{@post.title}」を削除しました"
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :image, :category_id)
  end

  def set_target_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_path
    else
      flash[:danger] = 'メールアドレスまたはパスワードが正しくありません'
      redirect_back fallback_location: login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      true
    else
      false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @posts = Post.order(created_at: :desc).limit(6)
      @popular_posts = Post.order('likes_count desc').limit(6)
      @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(6).pluck(:post_id))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_target_user, only: %i[show edit update likes]
  before_action :correct_user_page, only: %i[edit likes]
  before_action :require_user_logged_in?, only: %i[show edit update likes]

  def show
    @user = User.find(params[:id])
    @pagy,@posts = pagy(@user.posts.order(created_at: :desc), items: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def likes
    @posts = @user.posts
    @pagy,@like_posts = pagy(@user.like_posts.order(created_at: :desc), items: 10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile)
  end 

  def set_target_user
    @user = User.find(params[:id])
  end

  def correct_user_page
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment-group">
    <div class="comment_group_item ">
        <div class="top_item">
            <% if comment.user.image? %>
            <%= image_tag comment.user.image.url(:thumb2), class: "rounded-circle" %>
            <% else %>
            <%= image_tag "default.jpg", class: "rounded-circle", size: "70x70" %>
            <% end %>
        </div>
        <div class="comment_box">
            <div class="item_left">
                <p><b><%= link_to comment.user.name, comment.user, class: "link__name" %></b> :
                    <%= comment.created_at.to_s(:datetime_jp) %></p>
                <p><%= simple_format(comment.comment) %></p>
            </div>
            <div class="item_rigth">
                <% if logged_in? && current_user.id == comment.user_id %>
                <span><%= link_to '削除', [comment.post, comment],class: 'btn btn-outline-danger btn-sm',
                        method: :delete,
                        data: { confirm: "本当に削除してもよろしいですか？" } %></span>
                <% end %>
            </div>
        </div>
    </div>
</div>
<Hr>

app/views/comments/_form.html.erb
<%= form_with model:[ @post, @post.comments.build ], local:true do |f| %>
<div class="form-group">
    <%= f.label 'コメント (255文字未満)' %>
    <%= f.text_area :comment,class: 'form-control',rows: 4 %>
</div>
<div>
    <%= f.submit 'コメント投稿',class: 'btn btn-primary w-100' %>
</div>
<% end %>

app/views/likes/_like.html.erb
<% if logged_in? %>
  <% if current_user.like?(post) %>
    <%= link_to post_likes_path(post), method: :delete do %>
      <i class="fas fa-heart unlike-btn"></i>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post do %>
      <i class="fas fa-heart like-btn"></i>
    <% end %>
  <% end %>
    <%= post.likes.count %>
  <% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group"> 
    <%= f.label :title, 'タイトル(50文字未満)' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, '内容(10文字以上255文字未満)' %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, '画像をアップロード', class: "image_input_btn" %>
    <%= f.file_field :image, class: 'image_form' %>
  </div>
  <div class="form-input">
    <%= f.label :category_id, 'カテゴリー' %>
    <%= f.collection_select :category_id, Category.all, :id, :name,
            { prompt: '選択してください' },class: 'form-control' %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-primary w-100' %>
<% end %>

app/views/posts/index.html.erb
<div class="top__items">
  <h1 class="text-center">投稿一覧</h1>
  <div class="ml-auto posts__linkBox">
    <%= form_with url: posts_path, method: :get, class: 'posts__searchForm' do %>
    <%= select_tag :category_id,
                      options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
                      {
                        prompt: 'カテゴリーから探す',
                        class: 'form-control posts_select',
                        onchange: 'submit(this.form);'
                      } %>
    <% end %>
    <%= link_to '新規投稿', new_post_path, class: 'btn btn-outline-primary post__indexNew' %>
  </div>
  <%= render "layouts/posts_list", posts: @posts %>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/posts/new.html.erb
<div class="top__items">
<h1 class="text-center">新規投稿ページ</h1>
<%= render 'posts/form' %> 
<div>

app/views/posts/show.html.erb
<div class="top__items">
  
  <h4><b><%= @post.title %></b></h4>
    <Hr>
    <p><%= image_tag(@post.image.url, class: "img-responsive") if @post.image? %></p>
    <p><b><%= link_to @post.user.name, @post.user, class: "link__name" %></b> : <%= @post.created_at.to_s(:datetime_jp) %></p>
    <p><%= simple_format(@post.content) %></p>
    <p class="likes__items">いいね<i class="fas fa-heart unlike-btn" ></i> <%= @post.likes.count %> コメント<i class="far fa-comment-dots"></i> <%= @post.comments.length %></p>
    <p class="comment_count">
    <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>
  <div class="comment_list">
    <Hr>
    <p><%= render @post.comments %></p>
  </div> 
</div>
<h4>コメント投稿</h4>
<%= render "comments/form" %>

app/views/toppages/index.html.erb
<% if logged_in? %>
<div class="top__items">
<h1 class="text-center">Home</h1>
<h4>新着掲示板</h4>
  <%= render 'layouts/posts_list', posts: @posts %>
  <div class="home__moreWrap">
    <%= link_to 'もっと見る', posts_path, class: "home__more" %>
  </div>
  <h4>人気ランキング</h4>
<table class="table table-hover post__table">
  <thead class="thead__like">
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>作成日時</th>
      <th>いいね</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @post_like_ranks.each.with_index(1) do |post, i| %>
      <tr>
        <td class="phone__size"><% if post.user.image? %>                                                              
              <%= image_tag post.user.image.url(:thumb1), class: "rounded-circle" %>
            <% else %>
              <%= image_tag "default.jpg",class: "rounded-circle", size: "50x50" %>
            <% end %></td>
        <td class="phone__size"><%= link_to post.title.truncate(25), post, class: 'link__title' %></td>
        <td class="phone__size"><%= link_to post.user.name.truncate(6), post.user, class: 'link__name' %></td>
        <td class="phone__size"><%= post.created_at.to_s(:ymd) %></td>
        <td class="phone__size"><%= render 'likes/like', post: post %></td>
        <td class="phone__size"><i class="far fa-comment-dots"></i><%= post.comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
  <div class="main">
    <h1 class="masthead-heading text-uppercase mb-0">French Bulldog Posts</h1>
    <%= image_tag 'topimage.jpg', width: '100%', height: '80%'%>
    <div class="small__items">
    <h6 class="text-center"> I don't have time to worry about who doesn't like me. <br>  I'm too busy loving the people who love me.<i class="fas fa-heart"></i></h6></div>
    <div class="p-3 p-sm-5 my-4 rounded" >
      <div class="text-center text-brack">
        <h4>可愛いけど飼うのが大変だったりする<br>フレンチブルドッグに関する様々な情報をみんなで共有しよう</h4>
      <p class="signup__btn">
        <%= link_to '今すぐ登録！', signup_path, class: 'btn btn-lg btn-primary' %>
      </p>
      </div>
    </div>
  </div>
<% end %>
  

app/views/users/edit.html.erb
<div class="top__items">
  <div class="card">
    <div class="card-header">
      <h2><%= @user.name %> 編集ページ</h2>
    </div>
    <div class="card-body">
      <%= form_with model: @user do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <% if @user.image? %>
          <%= image_tag @user.image.url(:thumb), class:'rounded-circle' %>
        <% else %>
          <%= image_tag "default.jpg", class: 'rounded-circle', size: "150x150" %>
        <% end %>
        <hr>
        <p>
          <%= link_to 'マイページ', user_path, class: 'btn btn-outline-primary' %>
          <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>
        </p>
      <div class="form-group">
        <%= f.label :profile, 'プロフィール（255文字未満）' %>
        <%= f.text_area :profile, class: 'form-control', rows: 6  %>
      </div>
      <div class="form-group">
        <%= f.label :image, '画像をアップロード', class: "image_input_btn" %>
        <%= f.file_field :image, class: 'image_form' %>
      </div>
        <%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="top__items">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">お気に入り投稿</h3>
    </div>
    <div class="card-body">
      <%= link_to 'マイページ', user_path(current_user), class: 'btn btn-outline-primary' %>
      <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>
      <% if !@like_posts.empty? %>
        <% @like_posts.each do |post| %>
          <hr>
          <p><% if post.user.image? %>                                                              
                <%= image_tag post.user.image.url(:thumb1), class: "rounded-circle" %>
              <% else %>
                <%= image_tag "default.jpg",class: "rounded-circle", size: "50x50" %>
              <% end %></p>
          <p><b><%= link_to post.user.name, post.user, class: "link__name" %></b> :<%= post.created_at.to_s(:ymd)%></p>
          <p><% if logged_in? %>
            <% if current_user.like?(post)  %> 
              <%=link_to post_likes_path(post), method: :delete do %>
              <i class="fas fa-heart unlike-btn"></i>
            <% end %>
            <% else %>
              <%=link_to post_likes_path(post), method: :post do %>
              <i class="fas fa-heart like-btn"></i>
            <% end %>
            <% end %>
          <% end %><b><%= link_to post.title, post_path(post.id), class: "link__title" %></b> : <%= post.content %></p>
        <% end %>
      <% else %>
      <hr>
        <p>お気に入りの投稿はまだありません</p>
      <% end %>
      </div>
    </div>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/users/new.html.erb
<div class="signup__items">
  <h1>新規登録</h1>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with model: @user, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
        <div class="mb-3">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, 'パスワード(確認)' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '新規登録', class: 'btn btn-primary w-100' %>
      <% end %>
  </div>
</div>  

app/views/users/show.html.erb
<div class="top__items">
  <div class="card">
    <div class="card-header">
      <h2><%= @user.name %>マイページ</h2>
    </div>
    <div class="card-body">
      <% if @user.image? %>
        <%= image_tag @user.image.url(:thumb), class: "rounded-circle" %>
      <% else %>
        <%= image_tag "default.jpg", class: "rounded-circle", size: "150x150" %>
      <% end %>
      <h5 class="card-title">プロフィール</h5>
      <% if @user.profile.present? %>
        <p class="card-text"><%= simple_format(@user.profile) %></p>
      <% else %>
      <p>まだプロフィールが記入されていません</p>
      <% end %>

      <% if logged_in? && current_user == @user %>
        <%= link_to '編集ページ', edit_user_path(@user),class: 'btn btn-outline-success' %>
        <%= link_to 'お気に入り' , likes_user_path(current_user), class: 'btn btn-outline-info' %>
        <%= link_to '投稿一覧', posts_path, class: 'btn btn-outline-secondary' %>
      <% end %>
        <hr>
      <p>投稿履歴</p>
        <% if !@posts.empty? %>
        <% @posts.each do |post| %>
        <hr>
          <p><%= post.created_at.to_s(:ymd)%></p>
          <p><b><%= link_to post.title, post_path(post.id), class: "link__title" %></b>: <%= post.content %></p>
          <P>いいね<i class="fas fa-heart unlike-btn"></i> <%= post.likes.count %> コメント<i class="far fa-comment-dots"></i> <%= post.comments.count %>
            <span class="delete__btn">
            <% if logged_in? && current_user.id == post.user_id %>
              <%= link_to '削除', post_path(post.id), class: "btn btn-outline-danger", method: :delete, data: { confirm: '本当に削除してもよろしいですか?' } %>
            <% end %>
            </span>
          </P>
            
        <% end %>
        <% else %>
          <P>まだ投稿がありません</P>
        <% end %>
    </div>
  </div>
</div>
<%== pagy_bootstrap_nav(@pagy) %>