config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"

  get 'toppages/index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get :likes
    end
  end
  resources :categories, only: %i[create]
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :post, optional: true
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 255 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :categories
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save { email.downcase! }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false } 

  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :like_posts, through: :likes, source: :post

  def like(post)
    likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    like = likes.find_by(post_id: post.id)
    like.destroy if like
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        flash[:success] = 'コメントを投稿しました'
        redirect_to post_path(@post)
      else
        flash[:danger] = 'コメントの投稿に失敗しました'
        redirect_back(fallback_location: post_path)
      end
    end
  
    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      flash[:success] = 'コメントを削除しました'
      redirect_to post_path(@post)
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:comment)
    end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    flash[:success] = 'お気に入り登録しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    flash[:success] = 'お気に入り登録を外しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_target_post, only: %i[show destroy]
  before_action :require_user_logged_in?

  def index
    @pagy, @posts = pagy(params[:category_id].present? ? Category.find(params[:category_id]).posts.order('id DESC') : Post.order('id DESC'))
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "「#{@post.title}」を作成しました"
      redirect_to @post
    else   
      flash.now[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "「#{@post.title}」を削除しました"
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :image, :category_id)
  end

  def set_target_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_path
    else
      flash[:danger] = 'メールアドレスまたはパスワードが正しくありません'
      redirect_back fallback_location: login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      true
    else
      false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @posts = Post.order(created_at: :desc).limit(6)
      @popular_posts = Post.order('likes_count desc').limit(6)
      @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(6).pluck(:post_id))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_target_user, only: %i[show edit update likes]
  before_action :correct_user_page, only: %i[edit likes]
  before_action :require_user_logged_in?, only: %i[show edit update likes]

  def show
    @user = User.find(params[:id])
    @pagy,@posts = pagy(@user.posts.order(created_at: :desc), items: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def likes
    @posts = @user.posts
    @pagy,@like_posts = pagy(@user.like_posts.order(created_at: :desc), items: 10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile)
  end 

  def set_target_user
    @user = User.find(params[:id])
  end

  def correct_user_page
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>
  <small>
    &copy;French Bulldog Posts |
    <% if current_user %>
      <%= link_to 'マイページ', @current_user %>
      <%= link_to 'ログアウト',logout_path, method: :delete %>
    <% else %>
      <%= link_to '新規登録', signup_path %>
      <%= link_to 'ログイン', login_path %>
    <% end %>
  </small>
  </p>
</footer> 

app/views/layouts/_navbar.html.erb
<div class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark ">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">FrenchBulldogPosts</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <ul class="navbar-nav">
              <li class="ms-3"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to '投稿一覧', posts_path, class: 'nav-link' %></li>
              <li class="ms-3"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
            </ul>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to 'プロフィール', user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'お気に入り', likes_user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '新規登録', signup_path, class: 'nav-link' %>
            <%= link_to 'ログイン', login_path, class: 'nav-link' %>
          <% end %>
          </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_posts_list.html.erb
<table class="table table-hover posts__table">
  <thead class="thead">
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿日時</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th>
          <% if post.user.image? %>                                                              
            <%= image_tag post.user.image.url(:thumb1), class: "rounded-circle" %>
          <% else %>
            <%= image_tag "default.jpg",class: "rounded-circle", size: "50x50" %>
          <% end %>
        </th>
        <td class="phone__size">
          <span><%= link_to post.title.truncate(25), post, class: "link__title" %></span>
        </td>
        <td class="phone__size"><%= link_to post.user.name.truncate(6), post.user, class: "link__name" %></td>
        <td><span class="phone__size"><%= post.created_at.to_s(:ymd)%></span></td>
        <td class="phone__size"><%= render 'likes/like', post: post %></td>
        <td class="phone__size"><i class="far fa-comment-dots"></i><%= post.comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrenchBulldogPosts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>